# Generated by Django 4.1.7 on 2023-03-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2017-01-01', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default='7034725940'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='banna', max_length=255),
        ),
    ]
